### ISSUE TITLE
kotlinx.serialization.MissingFieldException

### ISSUE THREAD

**Issue by sebastianmarschall** [FinTecSystems/xs2a-android#11]
I am seeing following crashes from your SDK (4.0.0)

```
Fatal Exception: kotlinx.serialization.MissingFieldException: Field 'autocomplete' is required for type with serial name 'com.fintecsystems.xs2awizard.form.components.textLine.AutoCompleteResponse', but it was missing
       at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
       at com.fintecsystems.xs2awizard.form.components.textLine.AutoCompleteResponse.<init>(AutoCompleteResponse.kt:46)
       at com.fintecsystems.xs2awizard.form.components.textLine.AutoCompleteResponse$$serializer.deserialize(AutoCompleteResponse.kt:46)
       at com.fintecsystems.xs2awizard.form.components.textLine.AutoCompleteResponse$$serializer.deserialize(AutoCompleteResponse.kt:46)
       at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
       at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:36)
       at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
       at kotlinx.serialization.SerialFormatKt.decodeFromString(SerialFormatKt.java:97)
       at com.fintecsystems.xs2awizard.form.components.textLine.TextLineKt$TextLine$performAutoComplete$1$1.invoke(TextLine.kt:93)
       at com.fintecsystems.xs2awizard.form.components.textLine.TextLineKt$TextLine$performAutoComplete$1$1.invoke(TextLine.kt:91)
       at com.fintecsystems.xs2awizard_networking.NetworkingInstance.encodeAndSendMessage$lambda-0(NetworkingInstance.kt:86)
       at com.fintecsystems.xs2awizard_networking.NetworkingInstance.$r8$lambda$anHYWY7pjrOorpwbWet4a1oDsRg(NetworkingInstance.kt)
       at com.fintecsystems.xs2awizard_networking.NetworkingInstance$$InternalSyntheticLambda$1$603bad49cc5aa10912457230366f1aa136692984a135d348f18c12595be49418$0.onResponse(NetworkingInstance.java:4)
       at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
       at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by maik-mursall** [comment]
Hi @sebastianmarschall, thank you for your Issue.

Could you please provide me how you're able to reproduce this Bug?

Thanks in advance :)

**Comment by sebastianmarschall** [comment]
Hi @maik-mursall 
unfortunately not. I am only seeing it in my crash logs.

**Comment by maik-mursall** [comment]
Maybe the backend had a bad day then 🤷🏻 

Please report if you see this error more often. :)

**Comment by maik-mursall** [comment]
I will close this ticket now.
You can reopen it if this problem occurs again in the future :)
