### ISSUE TITLE
NumberFormatException   java.lang.Integer in parseInt - For input string: ""

### ISSUE THREAD

**Issue by ilkerkzgnC24** [FinTecSystems/xs2a-android#22]
Hi, we have been having this crash since the 21st of January and it is increasing day by day.

For more information here is the raw stack trace:

> java.lang.NumberFormatException: For input string: ""
    at java.lang.Integer.parseInt(Integer.java:807)
    at java.lang.Integer.parseInt(Integer.java:915)
    at kotlinx.serialization.json.JsonElementKt.getInt
    at com.fintecsystems.xs2awizard.form.components.RadioLineKt.RadioLine
    at com.fintecsystems.xs2awizard.XS2AWizardKt.FormLines
    at com.fintecsystems.xs2awizard.XS2AWizardKt.FormLinesContainer
    at com.fintecsystems.xs2awizard.XS2AWizardKt$XS2AWizard$2.invoke(SourceFile:115)
    at com.fintecsystems.xs2awizard.XS2AWizardKt$XS2AWizard$2.invoke(SourceFile:102)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:108)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:35)
    at androidx.compose.runtime.RecomposeScopeImpl.compose
    at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd
    at androidx.compose.runtime.ComposerImpl.skipCurrentGroup
    at androidx.compose.runtime.ComposerImpl.skipCurrentGroup
    at androidx.compose.runtime.ComposerImpl.doCompose
    at androidx.compose.runtime.ComposerImpl.doCompose
    at androidx.compose.runtime.ComposerImpl.recompose$runtime_release
    at androidx.compose.runtime.CompositionImpl.recompose
    at androidx.compose.runtime.CompositionImpl.recompose
    at androidx.compose.runtime.Recomposer.performRecompose
    at androidx.compose.runtime.Recomposer.access$performRecompose
    at androidx.compose.runtime.Recomposer.performRecompose
    at androidx.compose.runtime.Recomposer.access$performRecompose
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke
    at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame
    at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1648)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1129)
    at android.view.Choreographer.doFrame(Choreographer.java:1045)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8893)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by ilkerkzgnC24** [comment]
Pull request has been created by me [here](https://github.com/FinTecSystems/xs2a-android/pull/23).

**Comment by FriedrichSchlee** [comment]
Thank you, we will look at this and see when we can handle/merge it.
