### ISSUE TITLE
java.lang.NullPointerException: at com.fintecsystems.xs2awizard.form.components.RedirectLineKt.RedirectLine

### ISSUE THREAD

**Issue by vertin** [FinTecSystems/xs2a-android#27]
Hi,

Recently we received that crash for just one specific user.
The user had N26 bank account

Android 13
Samsung Galaxy S20
xs2a-android version: 5.2.1
Compose compiler: 1.5.11

Stacktrace:
```
java.lang.NullPointerException: null
    at com.fintecsystems.xs2awizard.form.components.RedirectLineKt.RedirectLine
    at com.fintecsystems.xs2awizard.XS2AWizardKt.FormLines
    at com.fintecsystems.xs2awizard.XS2AWizardKt.FormLinesContainer
    at com.fintecsystems.xs2awizard.XS2AWizardKt$XS2AWizard$2.invoke(SourceFile:120)
    at com.fintecsystems.xs2awizard.XS2AWizardKt$XS2AWizard$2.invoke(SourceFile:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:109)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:35)
    at androidx.compose.runtime.RecomposeScopeImpl.compose
    at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd
    at androidx.compose.runtime.ComposerImpl.skipCurrentGroup
    at androidx.compose.runtime.ComposerImpl.skipCurrentGroup
    at androidx.compose.runtime.ComposerImpl.doCompose
    at androidx.compose.runtime.changelist.ChangeList.isEmpty
    at androidx.compose.runtime.ComposerImpl.recompose$runtime_release
    at androidx.compose.runtime.ComposerImpl.recompose$runtime_release
    at androidx.compose.runtime.CompositionImpl.recompose
    at androidx.compose.runtime.CompositionImpl.recompose
    at androidx.compose.runtime.Recomposer.performRecompose
    at androidx.compose.runtime.Recomposer.access$performRecompose
    at androidx.compose.runtime.Recomposer.performRecompose
    at androidx.compose.runtime.Recomposer.access$performRecompose
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke
    at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke
    at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame
    at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
    at android.view.Choreographer.doCallbacks(Choreographer.java:923)
    at android.view.Choreographer.doFrame(Choreographer.java:847)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8762)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by vertin** [comment]
The crash happens here:
https://github.com/FinTecSystems/xs2a-android/blob/master/xs2awizard/src/main/java/com/fintecsystems/xs2awizard/form/components/RedirectLine.kt#L33

**Comment by FriedrichSchlee** [comment]
@vertin DO you have any transaction ids or sessions, where this happened for us?

**Comment by vertin** [comment]
Session ID(s): 
2bEb5AXyEAulLGD12Hb6OgsUdr6337FfE1S9JsJ0, 
E2Hkdqq4b9yDM48gxRKLJJ6jgN69RNgXFdnwEukQ

Tink Transaktion ID(s): 
13322-xp-hxXZ-INSV,
13322-xp-i44G-14a5

**Comment by FriedrichSchlee** [comment]
@vertin Can you please check, if it works now? Thank you

**Comment by FriedrichSchlee** [comment]
@vertin if it works now correct, please close this issue, Thank you

**Comment by vertin** [comment]
All good so far, 
Thank you
